# Generated by Django 4.2.10 on 2024-03-02 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ColorTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ImageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='LineTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MajorTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PostTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SentenceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SubTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SubLineTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.linetable', unique=True)),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.subtable')),
            ],
        ),
        migrations.CreateModel(
            name='SubColorTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.colortable', unique=True)),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.subtable')),
            ],
        ),
        migrations.CreateModel(
            name='PostSubTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_number', models.IntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.posttable')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.subtable', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostSentenceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_number', models.IntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.posttable')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.sentencetable', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostMajorTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_number', models.IntegerField()),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.majortable', unique=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.posttable')),
            ],
        ),
        migrations.CreateModel(
            name='PostImageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_number', models.IntegerField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.imagetable', unique=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.posttable')),
            ],
        ),
        migrations.CreateModel(
            name='PostChartTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_number', models.IntegerField()),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.charttable', unique=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.posttable')),
            ],
        ),
        migrations.CreateModel(
            name='MajorLineTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.linetable')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.majortable')),
            ],
        ),
        migrations.CreateModel(
            name='ChartCellTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell', models.TextField()),
                ('cell_number', models.IntegerField()),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.charttable')),
            ],
        ),
        migrations.CreateModel(
            name='ChartCellLineTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.chartcelltable')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.linetable')),
            ],
        ),
        migrations.CreateModel(
            name='ChartCellColorTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.chartcelltable')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.colortable')),
            ],
        ),
        migrations.CreateModel(
            name='AuthUserPostTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.posttable', unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuthGroupPostTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.posttable', unique=True)),
            ],
        ),
    ]
